### ISSUE TITLE
Bug: library make node.js process crashed

### ISSUE THREAD

**Issue by minons1** [openai/openai-realtime-api-beta#27]
```
Error: response.content_part.added: Item "item_AFz6bGwnCylAwlVNm27FW" not found
    at RealtimeConversation.response.content_part.added (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/conversation.js:179:15)
    at RealtimeConversation.processEvent (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/conversation.js:292:27)
    at handler (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/client.js:277:49)
    at RealtimeAPI.dispatch (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/event_handler.js:134:7)
    at RealtimeAPI.receive (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/api.js:178:10)
    at WebSocket.<anonymous> (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/api.js:129:14)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/Users/salim/gancang-guneman/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
    at Receiver.dataMessage (/Users/salim/gancang-guneman/node_modules/ws/lib/receiver.js:596:14)
[nodemon] app crashed - waiting for file changes before starting...
```

This crash happens ocassionally when I am trying to end the connection using `RealtimeClient` `.close()` method

**Comment by minons1** [comment]
Found another error that caused a crash

```
TypeError: Cannot set properties of undefined (setting 'audio_end_ms')
    at RealtimeConversation.input_audio_buffer.speech_stopped (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/conversation.js:130:27)
    at RealtimeConversation.processEvent (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/conversation.js:292:27)
    at handler (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/client.js:277:49)
    at file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/client.js:326:7
    at RealtimeAPI.dispatch (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/event_handler.js:134:7)
    at RealtimeAPI.receive (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/api.js:178:10)
    at WebSocket.<anonymous> (file:///Users/salim/gancang-guneman/node_modules/@openai/realtime-api-beta/lib/api.js:129:14)
    at WebSocket.emit (node:events:519:28)
    at Receiver.receiverOnMessage (/Users/salim/gancang-guneman/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:519:28)
```

**Comment by vcidst** [comment]
I've also been seeing them sporadically along with this one, usually happens after either of these

```
Already recording: please call .pause() first
    at WavRecorder.record (http://localhost:3000/static/js/bundle.js:45535:13)
    at startRecording (http://localhost:3000/static/js/bundle.js:629:23)
```

**Comment by khorwood-openai** [comment]
I've made a change which I expect to fix this:
https://github.com/openai/openai-realtime-api-beta/commit/339e9553a757ef1cf8c767272fc750c1e62effbb

Will close this for now, but feel free to re-open if the issue persists. It would be helpful if you could create a test case so I could add it to the library!

**Comment by Stevenic** [comment]
@khorwood-openai does that change address these issues as well?

https://github.com/openai/openai-realtime-api-beta/issues/12

**Comment by sam-cormack** [comment]
The "item not found" issues are still occurring with this change. I think it's because the event handlers are scheduled to run before `disconnect()` is called on the client, so they end up running after the call to `disconnect()` finishes and the conversation has been cleared, regardless of the ordering of calls within `disconnect`.

I think I've found a fix by having the event handlers check whether the client is connected before running anything. I also have a test case that triggers the error though it's a bit wonky as the error occurs after the test completes. 

I'll submit a PR.
